name: Manual

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Some parameter"
        default: "hello"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    env:
      IMAGE: "${{ github.repository }}"
      IMAGE_URL: "ghcr.io/${{ github.repository }}"
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Print env
        run: |
          set -exuo pipefail
          env

      - name: Dump github context
        run: echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Get image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ IMAGE_URL }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}},enable={{is_default_branch}}
            type=raw,value={{branch}}-{{sha}}-{{date 'X'}},enable=${{ !startsWith(github.ref, 'refs/tags/v') }}
          flavor: |
            latest=false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Show image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.3.0
        with:
          cosign-release: 'v2.2.2'

      - name: Check Cosign installation
        run: cosign version

      - name: Sign image
        run: |
          cosign sign --yes ${{ env.IMAGE_URL }}@${{ steps.docker_build.outputs.digest }}
          echo "Verify with:"
          echo "  cosign verify ${{ env.IMAGE_URL }}:${{ steps.meta.outputs.BUILD_ID }} \\"
          echo "    --certificate-identity=${{ github.server_url }}/${{ github.workflow_ref }} \\"
          echo "    --certificate-oidc-issuer=https://token.actions.githubusercontent.com"
